### ISSUE TITLE
Feature request: Include status of website in view

### ISSUE THREAD

**Issue by jannepn** [Juanito99/Windows.Server.Webservice.LogdirectoryWatcher#3]
It would be nice to have a column with the status of the website under "websites - IIS" view.
Eg. running, paused, stopped.

**Comment by Juanito99** [comment]
Technically looks possible, but I need to check if adding a new attribute would make the MP not compatible to older versions as the class changed. - Will test.

How about like this below?

![image](https://user-images.githubusercontent.com/11002556/37750940-81e9dff0-2dca-11e8-843c-d2f56b2ad4bd.png)

**Comment by jannepn** [comment]
Looks great, that was what I was l looking for.

**Comment by Juanito99** [comment]
Please have a try, updated the MP.  :)

**Comment by Juanito99** [comment]
Works as expected. :smile:
