### ISSUE TITLE
Some logdirectorys come back with no size 

### ISSUE THREAD

**Issue by jannepn** [Juanito99/Windows.Server.Webservice.LogdirectoryWatcher#4]
Example oif one working and one that is not working.
PS C:\admin> $webLogDirectory2 = "D:\logs\W3SVC16"

PS C:\admin> ((Get-ChildItem -Path $webLogDirectory2 | Measure-Object -property length -sum).Sum / 1MB)
66,0026407241821

PS C:\admin> [double]::TryParse(([Math]::Round(((Get-ChildItem -Path $webLogDirectory2 | Measure-Object -property length -sum).Sum / 1MB), 1)),[ref]$webLogDirSizeMB)
True

PS C:\admin> $webLogDirSizeMB
66

PS C:\admin> $webLogDirectory = "D:\logs\W3SVC14"

PS C:\admin> ((Get-ChildItem -Path $webLogDirectory | Measure-Object -property length -sum).Sum / 1MB)
129,689879417419

PS C:\admin> [double]::TryParse(([Math]::Round(((Get-ChildItem -Path $webLogDirectory | Measure-Object -property length -sum).Sum / 1MB), 1)),[ref]$webLogDirSizeMB)
False

PS C:\admin> $webLogDirSizeMB
0

PS C:\admin> [double]::TryParse([Math]::Round(((Get-ChildItem -Path $webLogDirectory2 | Measure-Object -property length -sum).Sum / 1MB), 1))
Cannot find an overload for "TryParse" and the argument count: "1".
At line:1 char:1
+ [double]::TryParse([Math]::Round(((Get-ChildItem -Path $webLogDirecto ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

**Comment by jannepn** [comment]
One thing to add is that in sweden we use "," for decimals. So the output looks a bit strange in my bug report. But powershell handles the conversion.  So I can repo the bug by using $sizetoround = 129.689879417419 and get nothing back from the round-function.

**Comment by Juanito99** [comment]
Thank you, that is very helpful feedback. Could you please run those lines in your environment and tell me what you get for both directories?

```powershell
try {
	$rawLogDirNoOfFiles   = 0	
	$rawLogDirNoOfFiles   = (Get-ChildItem -Path $webLogDirectory).Count
	$webLogDirNoOfFiles   = $rawLogDirNoOfFiles -as [double]

	$rawLogDirSize        = (Get-ChildItem -Path $webLogDirectory | Measure-Object -property length -sum).Sum / 1MB
	$doubleLogDirSize     = $rawLogDirSize -as [double]
	$webLogDirSizeMB      = [Math]::Round($doubleLogDirSize, 1)
} catch {
	$rawLogDirNoOfFiles   = 0	
	$webLogDirSizeMB      = 0
	
	$exceptionFullName    = $_.Exception.GetType().FullName
	$exceptionMessage     = $_.Exception.Message

Write-Host "Computer: $($computerName) checking for unconsidered $($discoveryItem) got errors for rawSize: $($doubleLogDirSize). `n $($exceptionFullName) `n $($exceptionMessage)")	
}
```

**Comment by jannepn** [comment]
Looks like it works fine now.

PS C:\admin> $webLogDirSizeMB
66

PS C:\admin> $webLogDirSizeMB
131,7

**Comment by Juanito99** [comment]
Updated the MP. - Please have a try :-)

**Comment by jannepn** [comment]
Woho! Directorysizes is now correct. I have updated version number on the community catalouge as well.

**Comment by Juanito99** [comment]
@jannepn Thank you very much ! :+1:
