### ISSUE TITLE
Sealed and nonselaed pack have different versions?

### ISSUE THREAD

**Issue by jannepn** [Juanito99/Windows.Server.Webservice.LogdirectoryWatcher#5]
The unsealed pack has .130 while the sealed pack has .129.

**Comment by Juanito99** [comment]
You're right. I guess it's because I am not using the configuration well in Visual Studio. I do a build for Release and the another one for Debug. - I will monitor that :)

**Comment by Juanito99** [comment]
Seems to be normal behavior in Visual Studio. I click on 'Build' to for the sealed version - e.g. number 99. The I click again on 'Build' to have an unsealed version and it gets number 100.

Sorry ^_^
