### ISSUE TITLE
When i try to import the SealedMP XML into scom 1801 I get this error

### ISSUE THREAD

**Issue by knlsystemhostingdk** [Juanito99/Windows.Server.Webservice.LogdirectoryWatcher#6]
This management pack cannot be imported.

: XSD verification failed for the management pack. [Line: 43, Position: 89]
'>' is an unexpected token. The expected token is '='. Line 43, position 89.

Im sure i can fix it, but if its a general issue.. :) 

Regards :) 
Kenneth

**Comment by Juanito99** [comment]
Hi Kenneth,

I will check this. Could you please see the OperationsManager log inside the eventvwr if there are some more information?

**Comment by knlsystemhostingdk** [comment]
The 1.0.0.129 build works... 
sorry i didnt get back to you. I forgot.. 

Shouldnt there be a recovery task, to reduce the size of the log files ?

**Comment by Juanito99** [comment]
Hi Kenneth,

the Recovery tasks are now in beta and been tested by two mates.
If all goes well I will update the version in the next week. :-)

**Comment by knlsystemhostingdk** [comment]
Sweet looking forward to that :)
